// بيانات التطبيقات والتصنيفات - يمكن تعديلها يدويًا أو عبر لوحة التحكم admin.html
const CATEGORIES = [
  {
    "slug": "ai",
    "name_ar": "أدوات الذكاء الاصطناعي",
    "name_en": "AI Tools",
    "icon": "🤖"
  },
  {
    "slug": "app-building",
    "name_ar": "بناء التطبيقات",
    "name_en": "App Building",
    "icon": "🛠️"
  },
  {
    "slug": "automation",
    "name_ar": "الأتمتة",
    "name_en": "Automation",
    "icon": "⚙️"
  },
  {
    "slug": "audio",
    "name_ar": "الصوت والصوتيات",
    "name_en": "Audio & Voice",
    "icon": "🎙️"
  },
  {
    "slug": "design",
    "name_ar": "التصميم",
    "name_en": "Design",
    "icon": "🎨"
  },
  {
    "slug": "digital-products",
    "name_ar": "المنتجات الرقمية",
    "name_en": "Digital Products",
    "icon": "💾"
  },
  {
    "slug": "articles",
    "name_ar": "المقالات والكتابة",
    "name_en": "Articles & Writing",
    "icon": "✍️"
  },
  {
    "slug": "images",
    "name_ar": "صور مجانية",
    "name_en": "Free Images",
    "icon": "🖼️"
  },
  {
    "slug": "google",
    "name_ar": "أدوات جوجل",
    "name_en": "Google Tools",
    "icon": "🔎"
  },
  {
    "slug": "marketing",
    "name_ar": "التسويق والتجارة",
    "name_en": "Marketing & E-commerce",
    "icon": "📈"
  },
  {
    "slug": "prompts",
    "name_ar": "البرومبت",
    "name_en": "Prompts",
    "icon": "💬"
  },
  {
    "slug": "tools",
    "name_ar": "أدوات عامة",
    "name_en": "General Tools",
    "icon": "🧰"
  },
  {
    "slug": "domains",
    "name_ar": "الدومينات والاستضافة",
    "name_en": "Domains & Hosting",
    "icon": "🌐"
  }
];

const APPS = [
  {
    "id": "ai-1",
    "category": "ai",
    "url": "https://www.notion.com",
    "domain": "www.notion.com",
    "name_ar": "Notion AI",
    "name_en": "Notion AI",
    "desc_ar": "مساحة عمل ذكية تجمع الملاحظات والمهام والذكاء الاصطناعي بمكان واحد.",
    "desc_en": "All-in-one workspace with AI-assisted notes, docs and task management."
  },
  {
    "id": "ai-2",
    "category": "ai",
    "url": "https://supersimple.com",
    "domain": "supersimple.com",
    "name_ar": "SuperSimple",
    "name_en": "SuperSimple",
    "desc_ar": "أداة تبسّط المهام المكتبية والتحليلية بمساعدة الذكاء الاصطناعي.",
    "desc_en": "AI tool that simplifies office and analytical tasks."
  },
  {
    "id": "ai-3",
    "category": "ai",
    "url": "https://www.easemate.ai/webapp/chat",
    "domain": "www.easemate.ai",
    "name_ar": "Easemate AI",
    "name_en": "Easemate AI",
    "desc_ar": "مساعد ذكاء اصطناعي للمحادثة وتلخيص المستندات والصفحات.",
    "desc_en": "AI chat assistant for summarizing documents and web pages."
  },
  {
    "id": "ai-4",
    "category": "ai",
    "url": "https://www.tasteatlas.com/map",
    "domain": "www.tasteatlas.com",
    "name_ar": "TasteAtlas",
    "name_en": "TasteAtlas",
    "desc_ar": "خريطة تفاعلية عالمية لاكتشاف الأكلات والمطابخ المحلية.",
    "desc_en": "Interactive world map for discovering local dishes and cuisines."
  },
  {
    "id": "ai-5",
    "category": "ai",
    "url": "https://atoms.dev/ar",
    "domain": "atoms.dev",
    "name_ar": "Atoms",
    "name_en": "Atoms",
    "desc_ar": "منصة لبناء تطبيقات وواجهات بمساعدة الذكاء الاصطناعي.",
    "desc_en": "Platform for building apps and interfaces with AI assistance."
  },
  {
    "id": "ai-6",
    "category": "ai",
    "url": "https://www.buzzy.now",
    "domain": "www.buzzy.now",
    "name_ar": "Buzzy",
    "name_en": "Buzzy",
    "desc_ar": "أداة ذكاء اصطناعي لإنشاء محتوى وأتمتة مهام صغيرة.",
    "desc_en": "AI tool for content creation and small task automation."
  },
  {
    "id": "ai-7",
    "category": "ai",
    "url": "https://tesana.ai/en",
    "domain": "tesana.ai",
    "name_ar": "Tesana AI",
    "name_en": "Tesana AI",
    "desc_ar": "منصة ذكاء اصطناعي لتوليد وتحرير المحتوى.",
    "desc_en": "AI platform for generating and editing content."
  },
  {
    "id": "ai-8",
    "category": "ai",
    "url": "https://doitong.com/ar",
    "domain": "doitong.com",
    "name_ar": "Doitong",
    "name_en": "Doitong",
    "desc_ar": "أداة ذكاء اصطناعي لإدارة المهام والإنتاجية.",
    "desc_en": "AI-powered productivity and task tool."
  },
  {
    "id": "ai-9",
    "category": "ai",
    "url": "https://phet.colorado.edu",
    "domain": "phet.colorado.edu",
    "name_ar": "PhET Simulations",
    "name_en": "PhET Simulations",
    "desc_ar": "محاكاة تفاعلية مجانية للفيزياء والعلوم من جامعة كولورادو.",
    "desc_en": "Free interactive science and physics simulations from University of Colorado."
  },
  {
    "id": "ai-10",
    "category": "ai",
    "url": "https://www.vascak.cz",
    "domain": "www.vascak.cz",
    "name_ar": "Vascak Physics",
    "name_en": "Vascak Physics",
    "desc_ar": "محاكاة تفاعلية لمفاهيم الفيزياء مثل الحركة الدائرية.",
    "desc_en": "Interactive physics simulations such as circular motion."
  },
  {
    "id": "ai-11",
    "category": "ai",
    "url": "https://animagraffs.com",
    "domain": "animagraffs.com",
    "name_ar": "Animagraffs",
    "name_en": "Animagraffs",
    "desc_ar": "إنفوجرافيك متحرك يشرح كيف تعمل الأشياء بطريقة بصرية ممتعة.",
    "desc_en": "Animated infographics that explain how things work."
  },
  {
    "id": "ai-12",
    "category": "ai",
    "url": "https://redpandaai.com",
    "domain": "redpandaai.com",
    "name_ar": "RedPanda AI",
    "name_en": "RedPanda AI",
    "desc_ar": "أدوات ذكاء اصطناعي لإنشاء محتوى مرئي وفيديو قصير.",
    "desc_en": "AI tools for creating short-form video and visual content."
  },
  {
    "id": "ai-13",
    "category": "ai",
    "url": "https://app.runwayml.com",
    "domain": "app.runwayml.com",
    "name_ar": "Runway",
    "name_en": "Runway",
    "desc_ar": "منصة رائدة في توليد وتحرير الفيديو بالذكاء الاصطناعي.",
    "desc_en": "Leading AI video generation and editing platform."
  },
  {
    "id": "ai-14",
    "category": "ai",
    "url": "https://www.topview.ai",
    "domain": "www.topview.ai",
    "name_ar": "TopView AI",
    "name_en": "TopView AI",
    "desc_ar": "أداة لإنشاء فيديوهات إعلانية تسويقية بالذكاء الاصطناعي.",
    "desc_en": "AI tool for creating marketing and ad videos."
  },
  {
    "id": "ai-15",
    "category": "ai",
    "url": "https://pollo.ai",
    "domain": "pollo.ai",
    "name_ar": "Pollo AI",
    "name_en": "Pollo AI",
    "desc_ar": "منصة توليد فيديو وصور بالذكاء الاصطناعي.",
    "desc_en": "AI platform for generating video and images."
  },
  {
    "id": "ai-16",
    "category": "ai",
    "url": "https://faceless.video",
    "domain": "faceless.video",
    "name_ar": "Faceless Video",
    "name_en": "Faceless Video",
    "desc_ar": "إنشاء فيديوهات بدون ظهور وجه باستخدام الذكاء الاصطناعي.",
    "desc_en": "Create faceless videos automatically using AI."
  },
  {
    "id": "ai-17",
    "category": "ai",
    "url": "https://www.doratoon.com/workplace",
    "domain": "www.doratoon.com",
    "name_ar": "Doratoon",
    "name_en": "Doratoon",
    "desc_ar": "أداة لإنشاء رسوم متحركة وفيديوهات كرتونية بسهولة.",
    "desc_en": "Tool for creating animated cartoon videos easily."
  },
  {
    "id": "ai-18",
    "category": "ai",
    "url": "https://abdallah.ai/r/remotion",
    "domain": "abdallah.ai",
    "name_ar": "Remotion Studio",
    "name_en": "Remotion Studio",
    "desc_ar": "أداة لإنشاء فيديوهات برمجيًا باستخدام React.",
    "desc_en": "Programmatic video creation tool built on React."
  },
  {
    "id": "ai-19",
    "category": "ai",
    "url": "https://arcadium3d.com",
    "domain": "arcadium3d.com",
    "name_ar": "Arcadium3D",
    "name_en": "Arcadium3D",
    "desc_ar": "توليد نماذج وعناصر ثلاثية الأبعاد بالذكاء الاصطناعي.",
    "desc_en": "AI-generated 3D models and assets."
  },
  {
    "id": "ai-20",
    "category": "ai",
    "url": "https://rokon.ai/ar",
    "domain": "rokon.ai",
    "name_ar": "Rokon AI",
    "name_en": "Rokon AI",
    "desc_ar": "أداة ذكاء اصطناعي لإنشاء محتوى رقمي.",
    "desc_en": "AI tool for digital content creation."
  },
  {
    "id": "ai-21",
    "category": "ai",
    "url": "https://higgsfield.ai",
    "domain": "higgsfield.ai",
    "name_ar": "Higgsfield AI",
    "name_en": "Higgsfield AI",
    "desc_ar": "منصة متقدمة لتوليد فيديوهات سينمائية بالذكاء الاصطناعي.",
    "desc_en": "Advanced AI platform for cinematic video generation."
  },
  {
    "id": "ai-22",
    "category": "ai",
    "url": "https://dreamina.capcut.com/tools/seedance-2-0",
    "domain": "dreamina.capcut.com",
    "name_ar": "Dreamina (CapCut)",
    "name_en": "Dreamina (CapCut)",
    "desc_ar": "أداة من CapCut لتوليد صور وفيديو بالذكاء الاصطناعي.",
    "desc_en": "CapCut's AI tool for image and video generation."
  },
  {
    "id": "ai-23",
    "category": "ai",
    "url": "https://tasawur.ai",
    "domain": "tasawur.ai",
    "name_ar": "Tasawur AI",
    "name_en": "Tasawur AI",
    "desc_ar": "أداة عربية لتوليد الصور والتصورات بالذكاء الاصطناعي.",
    "desc_en": "Arabic AI tool for generating images and visual concepts."
  },
  {
    "id": "ai-24",
    "category": "ai",
    "url": "https://kaiber.ai",
    "domain": "kaiber.ai",
    "name_ar": "Kaiber",
    "name_en": "Kaiber",
    "desc_ar": "منصة لتحويل الأفكار والموسيقى إلى فيديوهات فنية بالذكاء الاصطناعي.",
    "desc_en": "AI platform turning ideas and music into artistic videos."
  },
  {
    "id": "ai-25",
    "category": "ai",
    "url": "https://suno.com",
    "domain": "suno.com",
    "name_ar": "Suno AI",
    "name_en": "Suno AI",
    "desc_ar": "توليد أغاني وموسيقى كاملة بالذكاء الاصطناعي من نص بسيط.",
    "desc_en": "Generate full songs and music from a simple text prompt."
  },
  {
    "id": "ai-26",
    "category": "ai",
    "url": "https://app.pixverse.ai",
    "domain": "app.pixverse.ai",
    "name_ar": "PixVerse",
    "name_en": "PixVerse",
    "desc_ar": "أداة توليد فيديو قصير بالذكاء الاصطناعي من نص أو صورة.",
    "desc_en": "AI tool for generating short video from text or image."
  },
  {
    "id": "ai-27",
    "category": "ai",
    "url": "https://pictory.ai",
    "domain": "pictory.ai",
    "name_ar": "Pictory AI",
    "name_en": "Pictory AI",
    "desc_ar": "تحويل النصوص والمقالات إلى فيديوهات قصيرة تلقائيًا.",
    "desc_en": "Automatically turn articles and scripts into short videos."
  },
  {
    "id": "ai-28",
    "category": "ai",
    "url": "https://invideo.io",
    "domain": "invideo.io",
    "name_ar": "InVideo AI",
    "name_en": "InVideo AI",
    "desc_ar": "إنشاء فيديوهات احترافية من فكرة نصية بالذكاء الاصطناعي.",
    "desc_en": "Create professional videos from a text idea using AI."
  },
  {
    "id": "ai-29",
    "category": "ai",
    "url": "https://www.adobe.com",
    "domain": "www.adobe.com",
    "name_ar": "Adobe Creative Cloud",
    "name_en": "Adobe Creative Cloud",
    "desc_ar": "مجموعة أدوات أدوبي للتصميم والفيديو مع مزايا ذكاء اصطناعي.",
    "desc_en": "Adobe's design and video suite with built-in AI features."
  },
  {
    "id": "ai-30",
    "category": "ai",
    "url": "https://ai.byteplus.com/lumina/en",
    "domain": "ai.byteplus.com",
    "name_ar": "BytePlus Lumina",
    "name_en": "BytePlus Lumina",
    "desc_ar": "مجموعة أدوات ذكاء اصطناعي إبداعية من BytePlus.",
    "desc_en": "BytePlus's suite of creative AI tools."
  },
  {
    "id": "ai-31",
    "category": "ai",
    "url": "https://skywork.ai",
    "domain": "skywork.ai",
    "name_ar": "Skywork AI",
    "name_en": "Skywork AI",
    "desc_ar": "مساعد ذكاء اصطناعي لإنشاء المستندات والعروض والتقارير.",
    "desc_en": "AI assistant for creating documents, slides and reports."
  },
  {
    "id": "ai-32",
    "category": "ai",
    "url": "https://whacka.app/ar",
    "domain": "whacka.app",
    "name_ar": "Whacka",
    "name_en": "Whacka",
    "desc_ar": "أداة ذكاء اصطناعي عربية لإنشاء المحتوى.",
    "desc_en": "Arabic AI content creation tool."
  },
  {
    "id": "ai-33",
    "category": "ai",
    "url": "https://www.brmej.ai",
    "domain": "www.brmej.ai",
    "name_ar": "Brmej AI",
    "name_en": "Brmej AI",
    "desc_ar": "أداة عربية لتوليد المحتوى بالذكاء الاصطناعي.",
    "desc_en": "Arabic AI-powered content generation tool."
  },
  {
    "id": "ai-34",
    "category": "ai",
    "url": "https://www.designarena.ai",
    "domain": "www.designarena.ai",
    "name_ar": "Design Arena",
    "name_en": "Design Arena",
    "desc_ar": "منصة لمقارنة واختبار نماذج الذكاء الاصطناعي في التصميم.",
    "desc_en": "Platform for comparing AI models on design tasks."
  },
  {
    "id": "ai-35",
    "category": "ai",
    "url": "https://askaichat.app",
    "domain": "askaichat.app",
    "name_ar": "AskAI Chat",
    "name_en": "AskAI Chat",
    "desc_ar": "تطبيق يجمع عدة نماذج ذكاء اصطناعي للمحادثة والكتابة في مكان واحد.",
    "desc_en": "App bundling multiple AI chat models for writing and Q&A."
  },
  {
    "id": "ai-36",
    "category": "ai",
    "url": "https://www.kimi.com/en",
    "domain": "www.kimi.com",
    "name_ar": "Kimi",
    "name_en": "Kimi",
    "desc_ar": "مساعد ذكاء اصطناعي للمحادثة من شركة Moonshot AI.",
    "desc_en": "AI chat assistant by Moonshot AI."
  },
  {
    "id": "ai-37",
    "category": "ai",
    "url": "https://www.oreateai.com",
    "domain": "www.oreateai.com",
    "name_ar": "Oreate AI",
    "name_en": "Oreate AI",
    "desc_ar": "منصة توليد فيديو وصوت بالذكاء الاصطناعي.",
    "desc_en": "AI platform for video and voice generation."
  },
  {
    "id": "ai-38",
    "category": "ai",
    "url": "https://apps.apple.com/us/app/ai-video-ai-video-generator/id6478868302",
    "domain": "apps.apple.com",
    "name_ar": "AI Video Generator",
    "name_en": "AI Video Generator",
    "desc_ar": "تطبيق آيفون لتوليد فيديوهات بالذكاء الاصطناعي.",
    "desc_en": "iPhone app for AI-generated videos."
  },
  {
    "id": "ai-39",
    "category": "ai",
    "url": "https://www.perplexity.ai",
    "domain": "www.perplexity.ai",
    "name_ar": "Perplexity AI",
    "name_en": "Perplexity AI",
    "desc_ar": "محرك بحث بالذكاء الاصطناعي يجاوب بإجابات موثّقة بمصادر.",
    "desc_en": "AI search engine that answers with cited sources."
  },
  {
    "id": "ai-40",
    "category": "ai",
    "url": "https://claude.ai/login",
    "domain": "claude.ai",
    "name_ar": "Claude",
    "name_en": "Claude",
    "desc_ar": "مساعد ذكاء اصطناعي من Anthropic للمحادثة والكتابة والبرمجة.",
    "desc_en": "Anthropic's AI assistant for chat, writing and coding."
  },
  {
    "id": "ai-41",
    "category": "ai",
    "url": "https://app.heygen.com/home",
    "domain": "app.heygen.com",
    "name_ar": "HeyGen",
    "name_en": "HeyGen",
    "desc_ar": "إنشاء فيديوهات بأفاتار وصوت واقعي بالذكاء الاصطناعي.",
    "desc_en": "Create videos with realistic AI avatars and voices."
  },
  {
    "id": "ai-42",
    "category": "ai",
    "url": "https://elrebh.net",
    "domain": "elrebh.net",
    "name_ar": "الربح",
    "name_en": "Elrebh",
    "desc_ar": "موقع عربي يجمع طرق وأدوات للربح من الإنترنت.",
    "desc_en": "Arabic site listing ways and tools to earn money online."
  },
  {
    "id": "ai-43",
    "category": "ai",
    "url": "https://duckduckgo.com",
    "domain": "duckduckgo.com",
    "name_ar": "DuckDuckGo",
    "name_en": "DuckDuckGo",
    "desc_ar": "محرك بحث يحترم الخصوصية ولا يتتبع المستخدم.",
    "desc_en": "Privacy-focused search engine that doesn't track users."
  },
  {
    "id": "ai-44",
    "category": "ai",
    "url": "https://www.grammarly.com",
    "domain": "www.grammarly.com",
    "name_ar": "Grammarly",
    "name_en": "Grammarly",
    "desc_ar": "مساعد كتابة بالذكاء الاصطناعي لتصحيح وتحسين النصوص الإنجليزية.",
    "desc_en": "AI writing assistant for grammar and style in English."
  },
  {
    "id": "ai-45",
    "category": "ai",
    "url": "https://www.bing.com/images/create/ai-image-generator",
    "domain": "www.bing.com",
    "name_ar": "Bing Image Creator",
    "name_en": "Bing Image Creator",
    "desc_ar": "توليد صور بالذكاء الاصطناعي مجانًا من مايكروسوفت.",
    "desc_en": "Free AI image generation tool from Microsoft."
  },
  {
    "id": "ai-46",
    "category": "ai",
    "url": "https://www.synthesia.io",
    "domain": "www.synthesia.io",
    "name_ar": "Synthesia",
    "name_en": "Synthesia",
    "desc_ar": "إنشاء فيديوهات احترافية بأفاتار ذكاء اصطناعي بعدة لغات.",
    "desc_en": "Create professional videos with AI avatars in many languages."
  },
  {
    "id": "ai-47",
    "category": "ai",
    "url": "https://www.descript.com",
    "domain": "www.descript.com",
    "name_ar": "Descript",
    "name_en": "Descript",
    "desc_ar": "تحرير صوت وفيديو بالذكاء الاصطناعي عن طريق تعديل النص.",
    "desc_en": "Edit audio and video by editing text, powered by AI."
  },
  {
    "id": "automation-1",
    "category": "automation",
    "url": "https://n8n.io",
    "domain": "n8n.io",
    "name_ar": "n8n",
    "name_en": "n8n",
    "desc_ar": "أداة أتمتة مفتوحة المصدر لربط التطبيقات وبناء مسارات عمل تلقائية.",
    "desc_en": "Open-source automation tool for connecting apps and building workflows."
  },
  {
    "id": "tools-1",
    "category": "tools",
    "url": "https://tinywow.com",
    "domain": "tinywow.com",
    "name_ar": "TinyWow",
    "name_en": "TinyWow",
    "desc_ar": "مجموعة أدوات مجانية لتحرير الصور والفيديو وملفات PDF.",
    "desc_en": "Free suite of tools for images, video and PDF editing."
  },
  {
    "id": "tools-2",
    "category": "tools",
    "url": "https://hilltopads.com/login",
    "domain": "hilltopads.com",
    "name_ar": "HilltopAds",
    "name_en": "HilltopAds",
    "desc_ar": "شبكة إعلانية لعرض وإدارة الإعلانات على المواقع.",
    "desc_en": "Ad network for displaying and managing website ads."
  },
  {
    "id": "prompts-1",
    "category": "prompts",
    "url": "https://prompthero.com",
    "domain": "prompthero.com",
    "name_ar": "PromptHero",
    "name_en": "PromptHero",
    "desc_ar": "مكتبة ضخمة لبرومبتات الصور والفيديو بالذكاء الاصطناعي.",
    "desc_en": "Large library of prompts for AI image and video generation."
  },
  {
    "id": "prompts-2",
    "category": "prompts",
    "url": "https://www.meigen.ai",
    "domain": "www.meigen.ai",
    "name_ar": "Meigen AI",
    "name_en": "Meigen AI",
    "desc_ar": "أداة مساعدة لصياغة برومبتات احترافية للذكاء الاصطناعي.",
    "desc_en": "Tool for crafting professional AI prompts."
  },
  {
    "id": "prompts-3",
    "category": "prompts",
    "url": "https://aicameramovements.com",
    "domain": "aicameramovements.com",
    "name_ar": "AI Camera Movements",
    "name_en": "AI Camera Movements",
    "desc_ar": "مرجع لحركات الكاميرا السينمائية لاستخدامها في برومبتات الفيديو.",
    "desc_en": "Reference for cinematic camera moves to use in video prompts."
  },
  {
    "id": "prompts-4",
    "category": "prompts",
    "url": "https://enzozid.com/prompts.html",
    "domain": "enzozid.com",
    "name_ar": "Enzozid Prompts",
    "name_en": "Enzozid Prompts",
    "desc_ar": "مجموعة برومبتات جاهزة للاستخدام مع أدوات الذكاء الاصطناعي.",
    "desc_en": "Collection of ready-to-use prompts for AI tools."
  },
  {
    "id": "marketing-1",
    "category": "marketing",
    "url": "https://app.fieldagent.net",
    "domain": "app.fieldagent.net",
    "name_ar": "Field Agent",
    "name_en": "Field Agent",
    "desc_ar": "منصة لتنفيذ مهام ميدانية وأبحاث سوق مقابل أجر.",
    "desc_en": "Platform for paid field tasks and market research."
  },
  {
    "id": "marketing-2",
    "category": "marketing",
    "url": "https://affiliate.cjdropshipping.com",
    "domain": "affiliate.cjdropshipping.com",
    "name_ar": "CJ Dropshipping - Affiliate",
    "name_en": "CJ Dropshipping Affiliate",
    "desc_ar": "برنامج تسويق بالعمولة لمنصة CJ Dropshipping.",
    "desc_en": "Affiliate program for the CJ Dropshipping platform."
  },
  {
    "id": "marketing-3",
    "category": "marketing",
    "url": "https://affiliate-program.amazon.com",
    "domain": "affiliate-program.amazon.com",
    "name_ar": "Amazon Associates",
    "name_en": "Amazon Associates",
    "desc_ar": "برنامج أمازون للتسويق بالعمولة.",
    "desc_en": "Amazon's affiliate marketing program."
  },
  {
    "id": "marketing-4",
    "category": "marketing",
    "url": "https://temu.to/m/u43na3xawpu",
    "domain": "temu.to",
    "name_ar": "Temu",
    "name_en": "Temu",
    "desc_ar": "منصة تسوق إلكتروني عالمية بأسعار منخفضة.",
    "desc_en": "Global e-commerce shopping platform with low prices."
  },
  {
    "id": "marketing-5",
    "category": "marketing",
    "url": "https://medium.com",
    "domain": "medium.com",
    "name_ar": "Medium",
    "name_en": "Medium",
    "desc_ar": "منصة نشر مقالات وكتابة للمدونين والكتّاب.",
    "desc_en": "Publishing platform for articles and writers."
  },
  {
    "id": "marketing-6",
    "category": "marketing",
    "url": "https://cjdropshipping.com",
    "domain": "cjdropshipping.com",
    "name_ar": "CJ Dropshipping",
    "name_en": "CJ Dropshipping",
    "desc_ar": "منصة دروبشيبنج لإيجاد وشحن المنتجات للمتاجر الإلكترونية.",
    "desc_en": "Dropshipping platform for sourcing and shipping products."
  },
  {
    "id": "marketing-7",
    "category": "marketing",
    "url": "https://www.verdent.ai/ar",
    "domain": "www.verdent.ai",
    "name_ar": "Verdent AI",
    "name_en": "Verdent AI",
    "desc_ar": "أداة ذكاء اصطناعي للتسويق والمحتوى.",
    "desc_en": "AI tool for marketing and content."
  },
  {
    "id": "marketing-8",
    "category": "marketing",
    "url": "https://blazr.net",
    "domain": "blazr.net",
    "name_ar": "Blazr",
    "name_en": "Blazr",
    "desc_ar": "أداة لإدارة وتحسين حملات التسويق الرقمي.",
    "desc_en": "Tool for managing and optimizing digital marketing campaigns."
  },
  {
    "id": "marketing-9",
    "category": "marketing",
    "url": "https://www.etsy.com",
    "domain": "www.etsy.com",
    "name_ar": "Etsy",
    "name_en": "Etsy",
    "desc_ar": "سوق إلكتروني عالمي لبيع المنتجات اليدوية والإبداعية.",
    "desc_en": "Global marketplace for handmade and creative goods."
  },
  {
    "id": "marketing-10",
    "category": "marketing",
    "url": "https://www.easyorders.ai",
    "domain": "www.easyorders.ai",
    "name_ar": "Easy Orders",
    "name_en": "Easy Orders",
    "desc_ar": "نظام لإدارة طلبات المتاجر الإلكترونية والدروبشيبنج.",
    "desc_en": "Order management system for e-commerce and dropshipping."
  },
  {
    "id": "marketing-11",
    "category": "marketing",
    "url": "https://jo.iherb.com",
    "domain": "jo.iherb.com",
    "name_ar": "iHerb",
    "name_en": "iHerb",
    "desc_ar": "متجر عالمي لمنتجات الصحة والمكملات الغذائية.",
    "desc_en": "Global store for health products and supplements."
  },
  {
    "id": "marketing-12",
    "category": "marketing",
    "url": "https://www.alibaba.com",
    "domain": "www.alibaba.com",
    "name_ar": "Alibaba",
    "name_en": "Alibaba",
    "desc_ar": "منصة تجارة إلكترونية عالمية للشراء بالجملة من الموردين.",
    "desc_en": "Global B2B e-commerce platform for wholesale sourcing."
  },
  {
    "id": "marketing-13",
    "category": "marketing",
    "url": "https://c8ke.com",
    "domain": "c8ke.com",
    "name_ar": "C8ke",
    "name_en": "C8ke",
    "desc_ar": "أداة لتتبع وتحليل بيانات المنتجات والمتاجر.",
    "desc_en": "Tool for tracking and analyzing product and store data."
  },
  {
    "id": "marketing-14",
    "category": "marketing",
    "url": "https://www.kalodata.com",
    "domain": "www.kalodata.com",
    "name_ar": "Kalodata",
    "name_en": "Kalodata",
    "desc_ar": "أداة تحليل بيانات المنتجات الرائجة على TikTok Shop.",
    "desc_en": "Data analytics tool for trending TikTok Shop products."
  },
  {
    "id": "marketing-15",
    "category": "marketing",
    "url": "https://www.jasper.ai",
    "domain": "www.jasper.ai",
    "name_ar": "Jasper AI",
    "name_en": "Jasper AI",
    "desc_ar": "أداة ذكاء اصطناعي لكتابة محتوى تسويقي احترافي.",
    "desc_en": "AI tool for writing professional marketing content."
  },
  {
    "id": "marketing-16",
    "category": "marketing",
    "url": "https://www.dropship.io",
    "domain": "www.dropship.io",
    "name_ar": "Dropship.io",
    "name_en": "Dropship.io",
    "desc_ar": "أداة بحث عن منتجات رابحة للدروبشيبنج.",
    "desc_en": "Product research tool for finding winning dropshipping items."
  },
  {
    "id": "marketing-17",
    "category": "marketing",
    "url": "https://jobright.ai",
    "domain": "jobright.ai",
    "name_ar": "Jobright AI",
    "name_en": "Jobright AI",
    "desc_ar": "مساعد ذكاء اصطناعي للبحث عن وظائف وتحسين السيرة الذاتية.",
    "desc_en": "AI assistant for job search and resume optimization."
  },
  {
    "id": "marketing-18",
    "category": "marketing",
    "url": "https://durable.com",
    "domain": "durable.com",
    "name_ar": "Durable",
    "name_en": "Durable",
    "desc_ar": "إنشاء موقع ويب لعملك بالذكاء الاصطناعي خلال دقائق.",
    "desc_en": "Build a business website with AI in minutes."
  },
  {
    "id": "marketing-19",
    "category": "marketing",
    "url": "https://www.lightfunnels.com/ar",
    "domain": "www.lightfunnels.com",
    "name_ar": "LightFunnels",
    "name_en": "LightFunnels",
    "desc_ar": "منصة لبناء صفحات هبوط ومتاجر إلكترونية سريعة.",
    "desc_en": "Platform for building landing pages and fast online stores."
  },
  {
    "id": "digital-products-1",
    "category": "digital-products",
    "url": "https://gumroad.com",
    "domain": "gumroad.com",
    "name_ar": "Gumroad",
    "name_en": "Gumroad",
    "desc_ar": "منصة لبيع المنتجات الرقمية والكورسات مباشرة للجمهور.",
    "desc_en": "Platform for selling digital products and courses directly."
  },
  {
    "id": "digital-products-2",
    "category": "digital-products",
    "url": "https://payhip.com",
    "domain": "payhip.com",
    "name_ar": "Payhip",
    "name_en": "Payhip",
    "desc_ar": "منصة لبيع الكتب الرقمية والمنتجات والاشتراكات.",
    "desc_en": "Platform for selling ebooks, digital products and memberships."
  },
  {
    "id": "digital-products-3",
    "category": "digital-products",
    "url": "https://alfan.io/ar",
    "domain": "alfan.io",
    "name_ar": "Alfan",
    "name_en": "Alfan",
    "desc_ar": "منصة عربية لبيع المنتجات الرقمية والدورات.",
    "desc_en": "Arabic platform for selling digital products and courses."
  },
  {
    "id": "digital-products-4",
    "category": "digital-products",
    "url": "https://ko-fi.com",
    "domain": "ko-fi.com",
    "name_ar": "Ko-fi",
    "name_en": "Ko-fi",
    "desc_ar": "منصة لدعم المبدعين وبيع منتجات رقمية بسيطة.",
    "desc_en": "Platform for supporting creators and selling simple digital goods."
  },
  {
    "id": "digital-products-5",
    "category": "digital-products",
    "url": "https://digify.store",
    "domain": "digify.store",
    "name_ar": "Digify",
    "name_en": "Digify",
    "desc_ar": "متجر لبيع وحماية المنتجات الرقمية.",
    "desc_en": "Store for selling and protecting digital products."
  },
  {
    "id": "articles-1",
    "category": "articles",
    "url": "https://nathre.com/dashboard",
    "domain": "nathre.com",
    "name_ar": "Nathre",
    "name_en": "Nathre",
    "desc_ar": "أداة عربية لإنشاء مقالات ومحتوى بالذكاء الاصطناعي.",
    "desc_en": "Arabic AI tool for generating articles and content."
  },
  {
    "id": "articles-2",
    "category": "articles",
    "url": "https://seowriting.ai",
    "domain": "seowriting.ai",
    "name_ar": "SEOWriting AI",
    "name_en": "SEOWriting AI",
    "desc_ar": "أداة لكتابة مقالات متوافقة مع محركات البحث SEO بالذكاء الاصطناعي.",
    "desc_en": "AI tool for writing SEO-optimized articles."
  },
  {
    "id": "images-1",
    "category": "images",
    "url": "https://pixabay.com",
    "domain": "pixabay.com",
    "name_ar": "Pixabay",
    "name_en": "Pixabay",
    "desc_ar": "مكتبة صور وفيديوهات مجانية خالية من حقوق الملكية.",
    "desc_en": "Free library of royalty-free images and videos."
  },
  {
    "id": "google-1",
    "category": "google",
    "url": "https://workspace.google.com/products/vids/",
    "domain": "workspace.google.com",
    "name_ar": "Google Vids",
    "name_en": "Google Vids",
    "desc_ar": "أداة من جوجل لإنشاء فيديوهات عمل بسيطة بالذكاء الاصطناعي.",
    "desc_en": "Google's AI tool for creating simple work videos."
  },
  {
    "id": "google-2",
    "category": "google",
    "url": "https://www.dola.com/chat/",
    "domain": "www.dola.com",
    "name_ar": "Dola AI",
    "name_en": "Dola AI",
    "desc_ar": "مساعد ذكاء اصطناعي للجدولة والتذكير عبر المحادثة.",
    "desc_en": "AI chat assistant for scheduling and reminders."
  },
  {
    "id": "google-3",
    "category": "google",
    "url": "https://labs.google/fx/ar/tools/flow",
    "domain": "labs.google",
    "name_ar": "Google Flow",
    "name_en": "Google Flow",
    "desc_ar": "أداة تجريبية من Google Labs لإنشاء فيديو بالذكاء الاصطناعي.",
    "desc_en": "Experimental Google Labs tool for AI video creation."
  },
  {
    "id": "google-4",
    "category": "google",
    "url": "https://snapgen.ai",
    "domain": "snapgen.ai",
    "name_ar": "SnapGen AI",
    "name_en": "SnapGen AI",
    "desc_ar": "أداة لتوليد صور بالذكاء الاصطناعي بسرعة عالية.",
    "desc_en": "AI tool for fast image generation."
  },
  {
    "id": "google-5",
    "category": "google",
    "url": "https://vibes.ai",
    "domain": "vibes.ai",
    "name_ar": "Vibes AI",
    "name_en": "Vibes AI",
    "desc_ar": "أداة ذكاء اصطناعي لتوليد محتوى إبداعي.",
    "desc_en": "AI tool for creative content generation."
  },
  {
    "id": "google-6",
    "category": "google",
    "url": "https://docs.google.com",
    "domain": "docs.google.com",
    "name_ar": "Google Docs",
    "name_en": "Google Docs",
    "desc_ar": "محرر مستندات سحابي مجاني من جوجل.",
    "desc_en": "Google's free cloud document editor."
  },
  {
    "id": "google-7",
    "category": "google",
    "url": "https://gemini.google.com/app",
    "domain": "gemini.google.com",
    "name_ar": "Gemini",
    "name_en": "Gemini",
    "desc_ar": "مساعد الذكاء الاصطناعي من Google للمحادثة والإنتاجية.",
    "desc_en": "Google's AI assistant for chat and productivity."
  },
  {
    "id": "google-8",
    "category": "google",
    "url": "https://opal.google/landing/",
    "domain": "opal.google",
    "name_ar": "Google Opal",
    "name_en": "Google Opal",
    "desc_ar": "أداة تجريبية من جوجل لبناء تطبيقات ذكاء اصطناعي بدون كود.",
    "desc_en": "Google's experimental no-code AI app builder."
  },
  {
    "id": "google-9",
    "category": "google",
    "url": "https://ads.google.com/intl/ar/start/",
    "domain": "ads.google.com",
    "name_ar": "Google Ads",
    "name_en": "Google Ads",
    "desc_ar": "منصة جوجل لإنشاء وإدارة الحملات الإعلانية.",
    "desc_en": "Google's platform for creating and managing ad campaigns."
  },
  {
    "id": "google-10",
    "category": "google",
    "url": "https://developers.google.com/analytics?hl=ar",
    "domain": "developers.google.com",
    "name_ar": "Google Analytics",
    "name_en": "Google Analytics",
    "desc_ar": "أداة تحليل زوار وأداء المواقع من جوجل.",
    "desc_en": "Google's tool for tracking website traffic and performance."
  },
  {
    "id": "google-11",
    "category": "google",
    "url": "https://blog.google/innovation-and-ai/technology/ai/",
    "domain": "blog.google",
    "name_ar": "Google AI Blog",
    "name_en": "Google AI Blog",
    "desc_ar": "مدونة جوجل الرسمية لآخر أخبار وتحديثات الذكاء الاصطناعي.",
    "desc_en": "Google's official blog for AI news and updates."
  },
  {
    "id": "google-12",
    "category": "google",
    "url": "https://www.chatartpro.com",
    "domain": "www.chatartpro.com",
    "name_ar": "ChatArt Pro",
    "name_en": "ChatArt Pro",
    "desc_ar": "تطبيق دردشة وتوليد صور بالذكاء الاصطناعي.",
    "desc_en": "AI chat and image generation app."
  },
  {
    "id": "google-13",
    "category": "google",
    "url": "https://notebooklm.google.com",
    "domain": "notebooklm.google.com",
    "name_ar": "NotebookLM",
    "name_en": "NotebookLM",
    "desc_ar": "مساعد بحث وتدوين من جوجل يلخّص مصادرك الخاصة.",
    "desc_en": "Google's research assistant that summarizes your own sources."
  },
  {
    "id": "app-building-1",
    "category": "app-building",
    "url": "https://app.emergent.sh/landing/",
    "domain": "app.emergent.sh",
    "name_ar": "Emergent",
    "name_en": "Emergent",
    "desc_ar": "منصة لبناء تطبيقات كاملة بالذكاء الاصطناعي من وصف نصي.",
    "desc_en": "AI platform for building full apps from a text description."
  },
  {
    "id": "app-building-2",
    "category": "app-building",
    "url": "https://manus.im/login",
    "domain": "manus.im",
    "name_ar": "Manus",
    "name_en": "Manus",
    "desc_ar": "وكيل ذكاء اصطناعي عام لتنفيذ مهام معقدة تلقائيًا.",
    "desc_en": "General AI agent for executing complex tasks autonomously."
  },
  {
    "id": "app-building-3",
    "category": "app-building",
    "url": "https://replit.com/~",
    "domain": "replit.com",
    "name_ar": "Replit",
    "name_en": "Replit",
    "desc_ar": "بيئة تطوير سحابية للبرمجة وبناء التطبيقات بمساعدة الذكاء الاصطناعي.",
    "desc_en": "Cloud coding environment with AI-assisted app building."
  },
  {
    "id": "app-building-4",
    "category": "app-building",
    "url": "https://www.autocoder.cc/en/",
    "domain": "www.autocoder.cc",
    "name_ar": "Autocoder",
    "name_en": "Autocoder",
    "desc_ar": "أداة تحويل الأفكار إلى تطبيقات برمجية بالذكاء الاصطناعي.",
    "desc_en": "AI tool that turns ideas into working apps."
  },
  {
    "id": "domains-1",
    "category": "domains",
    "url": "https://www.namecheap.com/domains/registration/results/",
    "domain": "www.namecheap.com",
    "name_ar": "Namecheap",
    "name_en": "Namecheap",
    "desc_ar": "تسجيل أسماء نطاقات (دومينات) بأسعار تنافسية.",
    "desc_en": "Domain name registration at competitive prices."
  },
  {
    "id": "domains-2",
    "category": "domains",
    "url": "https://www.hostinger.com/ae",
    "domain": "www.hostinger.com",
    "name_ar": "Hostinger",
    "name_en": "Hostinger",
    "desc_ar": "خدمات استضافة مواقع وتسجيل دومينات بأسعار مناسبة.",
    "desc_en": "Web hosting and domain registration services."
  },
  {
    "id": "audio-1",
    "category": "audio",
    "url": "https://lahajati.ai/login",
    "domain": "lahajati.ai",
    "name_ar": "لهجاتي AI",
    "name_en": "Lahajati AI",
    "desc_ar": "أداة تحويل النص إلى كلام باللهجات العربية المختلفة.",
    "desc_en": "Arabic dialect text-to-speech AI tool."
  },
  {
    "id": "audio-2",
    "category": "audio",
    "url": "https://elevenlabs.io",
    "domain": "elevenlabs.io",
    "name_ar": "ElevenLabs",
    "name_en": "ElevenLabs",
    "desc_ar": "أداة رائدة لتحويل النص إلى صوت واقعي واستنساخ الأصوات.",
    "desc_en": "Leading AI text-to-speech and voice cloning tool."
  },
  {
    "id": "audio-3",
    "category": "audio",
    "url": "https://www.minimax.io",
    "domain": "www.minimax.io",
    "name_ar": "MiniMax",
    "name_en": "MiniMax",
    "desc_ar": "منصة ذكاء اصطناعي متعددة الوسائط للصوت والفيديو والنص.",
    "desc_en": "Multimodal AI platform for audio, video and text."
  },
  {
    "id": "audio-4",
    "category": "audio",
    "url": "https://voicebox.sh/download",
    "domain": "voicebox.sh",
    "name_ar": "Voicebox",
    "name_en": "Voicebox",
    "desc_ar": "أداة لتوليد وتحرير الأصوات بالذكاء الاصطناعي.",
    "desc_en": "AI tool for generating and editing voices."
  },
  {
    "id": "audio-5",
    "category": "audio",
    "url": "https://murf.ai",
    "domain": "murf.ai",
    "name_ar": "Murf AI",
    "name_en": "Murf AI",
    "desc_ar": "استوديو تحويل نص إلى صوت احترافي للفيديوهات والعروض.",
    "desc_en": "Professional text-to-speech studio for videos and presentations."
  },
  {
    "id": "design-1",
    "category": "design",
    "url": "https://www.canva.com/ar/login/",
    "domain": "www.canva.com",
    "name_ar": "Canva",
    "name_en": "Canva",
    "desc_ar": "أداة تصميم جرافيك سهلة للجميع مع ميزات ذكاء اصطناعي.",
    "desc_en": "Easy graphic design tool for everyone with AI features."
  },
  {
    "id": "design-2",
    "category": "design",
    "url": "https://looka.com",
    "domain": "looka.com",
    "name_ar": "Looka",
    "name_en": "Looka",
    "desc_ar": "أداة لتصميم شعارات وهوية بصرية بالذكاء الاصطناعي.",
    "desc_en": "AI tool for designing logos and brand identity."
  },
  {
    "id": "ai-new-metaai",
    "category": "ai",
    "url": "https://www.meta.ai/",
    "domain": "www.meta.ai",
    "name_ar": "ميتا AI",
    "name_en": "Meta AI",
    "desc_ar": "مساعد ذكاء اصطناعي من ميتا للمحادثة وتوليد الصور والإجابة على الأسئلة.",
    "desc_en": "Meta's AI assistant for chat, image generation and answering questions."
  },
  {
    "id": "audio-new-mureka",
    "category": "audio",
    "url": "https://www.mureka.ai/create",
    "domain": "www.mureka.ai",
    "name_ar": "Mureka AI",
    "name_en": "Mureka AI",
    "desc_ar": "منصة لتوليد أغاني وموسيقى كاملة بالذكاء الاصطناعي من كلمات أو وصف نصي.",
    "desc_en": "AI platform for generating full songs and music from lyrics or a text prompt."
  },
  {
    "id": "ai-new-pixella",
    "category": "ai",
    "url": "https://pixella.ai/text-to-video-ai",
    "domain": "pixella.ai",
    "name_ar": "Pixella AI",
    "name_en": "Pixella AI",
    "desc_ar": "أداة لتحويل النص إلى فيديو بالذكاء الاصطناعي.",
    "desc_en": "AI tool for turning text into video."
  },
  {
    "id": "ai-new-freeai",
    "category": "ai",
    "url": "https://free.ai/",
    "domain": "free.ai",
    "name_ar": "Free AI",
    "name_en": "Free AI",
    "desc_ar": "منصة تجمع أدوات ذكاء اصطناعي مجانية للاستخدام المباشر.",
    "desc_en": "Platform offering free AI tools for direct use."
  },
  {
    "id": "marketing-new-autods",
    "category": "marketing",
    "url": "https://platform.autods.com/choose-plan",
    "domain": "platform.autods.com",
    "name_ar": "AutoDS",
    "name_en": "AutoDS",
    "desc_ar": "منصة أتمتة الدروبشيبنج لإدارة المنتجات والطلبات والأسعار تلقائيًا عبر عدة متاجر.",
    "desc_en": "Dropshipping automation platform for managing products, orders and pricing across stores."
  },
  {
    "id": "ai-new-imagineart",
    "category": "ai",
    "url": "https://www.imagine.art/",
    "domain": "www.imagine.art",
    "name_ar": "Imagine Art",
    "name_en": "Imagine Art",
    "desc_ar": "منصة لتوليد وتحرير الصور والفن الرقمي بالذكاء الاصطناعي.",
    "desc_en": "AI platform for generating and editing images and digital art."
  },
  {
    "id": "ai-new-midjourney",
    "category": "ai",
    "url": "https://www.midjourney.com/explore",
    "domain": "www.midjourney.com",
    "name_ar": "Midjourney",
    "name_en": "Midjourney",
    "desc_ar": "من أشهر أدوات توليد الصور الفنية بالذكاء الاصطناعي بجودة عالية.",
    "desc_en": "One of the most popular AI tools for generating high-quality artistic images."
  },
  {
    "id": "ai-new-chatgpt",
    "category": "ai",
    "url": "https://chatgpt.com/",
    "domain": "chatgpt.com",
    "name_ar": "ChatGPT",
    "name_en": "ChatGPT",
    "desc_ar": "مساعد الذكاء الاصطناعي الأشهر عالميًا للمحادثة والكتابة والإجابة على الأسئلة وتحليل المحتوى.",
    "desc_en": "The world's most popular AI assistant for chat, writing, Q&A and content analysis."
  },
  {
    "id": "ai-new-tome",
    "category": "ai",
    "url": "https://tome.app/",
    "domain": "tome.app",
    "name_ar": "Tome",
    "name_en": "Tome",
    "desc_ar": "أداة لإنشاء عروض تقديمية احترافية بسرعة باستخدام الذكاء الاصطناعي.",
    "desc_en": "AI tool for quickly creating professional presentations."
  },
  {
    "id": "ai-new-tabnine",
    "category": "ai",
    "url": "https://www.tabnine.com/",
    "domain": "www.tabnine.com",
    "name_ar": "Tabnine",
    "name_en": "Tabnine",
    "desc_ar": "مساعد برمجي بالذكاء الاصطناعي يكتب أكواد ويقترح حلولًا داخل بيئة التطوير.",
    "desc_en": "AI coding assistant that writes code and suggests solutions in your IDE."
  },
  {
    "id": "ai-new-characterai",
    "category": "ai",
    "url": "https://character.ai/",
    "domain": "character.ai",
    "name_ar": "Character.AI",
    "name_en": "Character.AI",
    "desc_ar": "منصة لإنشاء شخصيات ذكاء اصطناعي والدردشة معها بمحادثات واقعية.",
    "desc_en": "Platform for creating AI characters and chatting with them realistically."
  },
  {
    "id": "ai-new-copyai",
    "category": "ai",
    "url": "https://www.copy.ai/",
    "domain": "www.copy.ai",
    "name_ar": "Copy.ai",
    "name_en": "Copy.ai",
    "desc_ar": "أداة كتابة محتوى تسويقي وإعلاني بالذكاء الاصطناعي بأكثر من 25 لغة.",
    "desc_en": "AI copywriting tool for marketing content in 25+ languages."
  },
  {
    "id": "ai-new-tryellie",
    "category": "ai",
    "url": "https://tryellie.com/",
    "domain": "tryellie.com",
    "name_ar": "Tryellie",
    "name_en": "Tryellie",
    "desc_ar": "يردّ على الإيميلات نيابة عنك بأسلوب كتابتك واحترافية.",
    "desc_en": "Replies to your emails in your own writing style, professionally."
  },
  {
    "id": "automation-new-godmode",
    "category": "automation",
    "url": "https://godmode.space/",
    "domain": "godmode.space",
    "name_ar": "GodMode",
    "name_en": "GodMode",
    "desc_ar": "منصة تشغّل وكلاء ذكاء اصطناعي مستقلين (مثل Auto-GPT) لتنفيذ مهام معقدة تلقائيًا.",
    "desc_en": "Platform for running autonomous AI agents (like Auto-GPT) to execute complex tasks."
  },
  {
    "id": "ai-new-fireflies",
    "category": "ai",
    "url": "https://fireflies.ai/",
    "domain": "fireflies.ai",
    "name_ar": "Fireflies",
    "name_en": "Fireflies",
    "desc_ar": "يسجّل الاجتماعات ويحوّلها لنصوص وملخصات تلقائيًا.",
    "desc_en": "Records meetings and turns them into transcripts and summaries automatically."
  },
  {
    "id": "ai-new-stockimgai",
    "category": "ai",
    "url": "https://stockimg.ai/",
    "domain": "stockimg.ai",
    "name_ar": "Stockimg AI",
    "name_en": "Stockimg AI",
    "desc_ar": "توليد صور عالية الجودة وخالية من حقوق الملكية بالذكاء الاصطناعي.",
    "desc_en": "Generates high-quality, royalty-free images using AI."
  },
  {
    "id": "ai-new-tripnotes",
    "category": "ai",
    "url": "https://tripnotes.ai/",
    "domain": "tripnotes.ai",
    "name_ar": "Tripnotes",
    "name_en": "Tripnotes",
    "desc_ar": "يخطط لرحلتك ويجمع معلومات سفر في كل موقع بالذكاء الاصطناعي.",
    "desc_en": "AI travel planner that gathers info about every stop on your trip."
  },
  {
    "id": "ai-new-myaifrontdesk",
    "category": "ai",
    "url": "https://www.myaifrontdesk.com/",
    "domain": "www.myaifrontdesk.com",
    "name_ar": "My AI Front Desk",
    "name_en": "My AI Front Desk",
    "desc_ar": "موظف استقبال ذكي يرد على مكالمات الشركة ويخدم العملاء 24/7.",
    "desc_en": "AI receptionist that answers business calls and serves customers 24/7."
  },
  {
    "id": "domains-new-namy",
    "category": "domains",
    "url": "https://namy.ai/",
    "domain": "namy.ai",
    "name_ar": "Namy",
    "name_en": "Namy",
    "desc_ar": "يقترح أسماء وأدوماينات مميزة لمشروعك ويتحقق من توفرها فورًا.",
    "desc_en": "Suggests catchy business names and domains, checking availability instantly."
  },
  {
    "id": "ai-new-undetectableai",
    "category": "ai",
    "url": "https://undetectable.ai/",
    "domain": "undetectable.ai",
    "name_ar": "Undetectable AI",
    "name_en": "Undetectable AI",
    "desc_ar": "يعيد صياغة النصوص لتبدو مكتوبة بشرية بنسبة 100% وتتجاوز كاشفات الذكاء الاصطناعي.",
    "desc_en": "Rewrites AI text to read as 100% human and bypass AI detectors."
  },
  {
    "id": "ai-new-askyourpdf",
    "category": "ai",
    "url": "https://askyourpdf.com/",
    "domain": "askyourpdf.com",
    "name_ar": "AskYourPDF",
    "name_en": "AskYourPDF",
    "desc_ar": "تلخيص وطرح أسئلة والاستخراج من ملفات PDF مباشرة بالذكاء الاصطناعي.",
    "desc_en": "Summarize, question, and extract info from PDF files directly with AI."
  },
  {
    "id": "ai-new-quillbot",
    "category": "ai",
    "url": "https://quillbot.com/",
    "domain": "quillbot.com",
    "name_ar": "QuillBot",
    "name_en": "QuillBot",
    "desc_ar": "أداة لإعادة صياغة النصوص وتدقيقها وترجمتها بالذكاء الاصطناعي.",
    "desc_en": "AI tool for paraphrasing, proofreading and translating text."
  },
  {
    "id": "design-new-lensa",
    "category": "design",
    "url": "https://prisma-ai.com/lensa",
    "domain": "prisma-ai.com",
    "name_ar": "Lensa",
    "name_en": "Lensa",
    "desc_ar": "تحرير الصور وإنشاء صور رمزية فنية مميزة وتأثيرات احترافية بالذكاء الاصطناعي.",
    "desc_en": "AI photo editor for professional retouching and unique artistic avatars."
  },
  {
    "id": "ai-new-replika",
    "category": "ai",
    "url": "https://replika.com/",
    "domain": "replika.com",
    "name_ar": "Replika",
    "name_en": "Replika",
    "desc_ar": "رفيق افتراضي ذكي يتفاعل معك بمحادثات يومية ويتذكر تفاصيلك.",
    "desc_en": "A smart AI companion that chats with you daily and remembers your details."
  },
  {
    "id": "design-new-microsoftdesigner",
    "category": "design",
    "url": "https://designer.microsoft.com/",
    "domain": "designer.microsoft.com",
    "name_ar": "Microsoft Designer",
    "name_en": "Microsoft Designer",
    "desc_ar": "أداة من مايكروسوفت لإنشاء تصاميم احترافية (بوسترات، منشورات، دعوات) بالذكاء الاصطناعي.",
    "desc_en": "Microsoft's AI tool for creating professional designs (posters, posts, invitations)."
  },
  {
    "id": "ai-new2-microsoftcopilot",
    "category": "ai",
    "url": "https://copilot.microsoft.com/",
    "domain": "copilot.microsoft.com",
    "name_ar": "Microsoft Copilot",
    "name_en": "Microsoft Copilot",
    "desc_ar": "مساعد ذكاء اصطناعي من مايكروسوفت للمحادثة والبحث والمساعدة بالكتابة.",
    "desc_en": "Microsoft's AI assistant for chat, search and writing help."
  },
  {
    "id": "ai-new2-leonardoai",
    "category": "ai",
    "url": "https://leonardo.ai/",
    "domain": "leonardo.ai",
    "name_ar": "Leonardo AI",
    "name_en": "Leonardo AI",
    "desc_ar": "توليد صور احترافية بدقة عالية وخيارات تخصيص متعددة.",
    "desc_en": "Generate high-quality professional images with many customization options."
  },
  {
    "id": "ai-new2-pika",
    "category": "ai",
    "url": "https://pika.art/",
    "domain": "pika.art",
    "name_ar": "Pika",
    "name_en": "Pika",
    "desc_ar": "إنشاء وتعديل فيديو بالذكاء الاصطناعي بسهولة وسرعة.",
    "desc_en": "Create and edit video with AI, easily and quickly."
  },
  {
    "id": "audio-new2-playht",
    "category": "audio",
    "url": "https://play.ht/",
    "domain": "play.ht",
    "name_ar": "PlayHT",
    "name_en": "PlayHT",
    "desc_ar": "تحويل النص إلى صوت طبيعي بأصوات واقعية متعددة اللغات.",
    "desc_en": "Natural text-to-speech with realistic multilingual voices."
  },
  {
    "id": "ai-new2-marketmuse",
    "category": "ai",
    "url": "https://www.marketmuse.com/",
    "domain": "www.marketmuse.com",
    "name_ar": "MarketMuse",
    "name_en": "MarketMuse",
    "desc_ar": "تخطيط وتحسين محتوى SEO بالذكاء الاصطناعي.",
    "desc_en": "AI-powered content planning and SEO optimization."
  },
  {
    "id": "ai-new2-clearscope",
    "category": "ai",
    "url": "https://www.clearscope.io/",
    "domain": "www.clearscope.io",
    "name_ar": "Clearscope",
    "name_en": "Clearscope",
    "desc_ar": "تحسين محتوى المقالات ليتصدّر نتائج البحث بالذكاء الاصطناعي.",
    "desc_en": "AI tool for optimizing content to rank higher in search results."
  },
  {
    "id": "ai-new2-chatfuel",
    "category": "ai",
    "url": "https://www.chatfuel.com/",
    "domain": "www.chatfuel.com",
    "name_ar": "Chatfuel",
    "name_en": "Chatfuel",
    "desc_ar": "بناء روبوتات محادثة للمبيعات وخدمة العملاء بدون كود.",
    "desc_en": "Build no-code chatbots for sales and customer service."
  },
  {
    "id": "ai-new2-droxy",
    "category": "ai",
    "url": "https://droxy.ai/",
    "domain": "droxy.ai",
    "name_ar": "Droxy",
    "name_en": "Droxy",
    "desc_ar": "بناء روبوت محادثة ذكي مدرّب على بيانات عملك.",
    "desc_en": "Build an AI chatbot trained on your own business data."
  },
  {
    "id": "ai-new2-chatsimple",
    "category": "ai",
    "url": "https://www.chatsimple.ai/",
    "domain": "www.chatsimple.ai",
    "name_ar": "ChatSimple",
    "name_en": "ChatSimple",
    "desc_ar": "روبوت محادثة ذكي يجيب على عملاء موقعك تلقائيًا.",
    "desc_en": "AI chatbot that automatically answers your website visitors."
  },
  {
    "id": "ai-new2-chatbase",
    "category": "ai",
    "url": "https://www.chatbase.co/",
    "domain": "www.chatbase.co",
    "name_ar": "Chatbase",
    "name_en": "Chatbase",
    "desc_ar": "بناء روبوت دردشة مخصص من بيانات موقعك أو مستنداتك.",
    "desc_en": "Build a custom chatbot trained on your website or documents."
  },
  {
    "id": "google-new2-dialogflow",
    "category": "google",
    "url": "https://dialogflow.cloud.google.com/",
    "domain": "dialogflow.cloud.google.com",
    "name_ar": "Dialogflow",
    "name_en": "Dialogflow",
    "desc_ar": "منصة جوجل لبناء روبوتات محادثة صوتية ونصية.",
    "desc_en": "Google's platform for building voice and text conversational bots."
  },
  {
    "id": "design-new2-logoai",
    "category": "design",
    "url": "https://www.logoai.com/",
    "domain": "www.logoai.com",
    "name_ar": "Logo AI",
    "name_en": "Logo AI",
    "desc_ar": "تصميم شعار احترافي لعلامتك التجارية خلال دقائق بالذكاء الاصطناعي.",
    "desc_en": "Design a professional brand logo in minutes with AI."
  },
  {
    "id": "design-new2-brandmark",
    "category": "design",
    "url": "https://brandmark.io/",
    "domain": "brandmark.io",
    "name_ar": "Brandmark",
    "name_en": "Brandmark",
    "desc_ar": "توليد شعار وهوية بصرية متكاملة بالذكاء الاصطناعي.",
    "desc_en": "AI-generated logo and complete brand identity."
  },
  {
    "id": "automation-new2-zapier",
    "category": "automation",
    "url": "https://zapier.com/",
    "domain": "zapier.com",
    "name_ar": "Zapier",
    "name_en": "Zapier",
    "desc_ar": "ربط تطبيقاتك ببعضها وأتمتة المهام المتكررة تلقائيًا.",
    "desc_en": "Connect your apps and automate repetitive tasks."
  },
  {
    "id": "ai-new2-seaartai",
    "category": "ai",
    "url": "https://www.seaart.ai/",
    "domain": "www.seaart.ai",
    "name_ar": "SeaArt AI",
    "name_en": "SeaArt AI",
    "desc_ar": "توليد صور فنية وشخصيات أنمي بالذكاء الاصطناعي.",
    "desc_en": "AI-generated artwork and anime-style character images."
  },
  {
    "id": "ai-new2-gencraft",
    "category": "ai",
    "url": "https://gencraft.com/",
    "domain": "gencraft.com",
    "name_ar": "Gencraft",
    "name_en": "Gencraft",
    "desc_ar": "توليد صور وفن رقمي من نص بالذكاء الاصطناعي.",
    "desc_en": "AI text-to-image and digital art generator."
  },
  {
    "id": "ai-new2-clarifai",
    "category": "ai",
    "url": "https://www.clarifai.com/",
    "domain": "www.clarifai.com",
    "name_ar": "Clarifai",
    "name_en": "Clarifai",
    "desc_ar": "منصة رؤية حاسوبية للتعرف على الصور والفيديو بالذكاء الاصطناعي.",
    "desc_en": "AI computer vision platform for image and video recognition."
  },
  {
    "id": "ai-new2-writesonic",
    "category": "ai",
    "url": "https://writesonic.com/",
    "domain": "writesonic.com",
    "name_ar": "Writesonic",
    "name_en": "Writesonic",
    "desc_ar": "كتابة مقالات ومحتوى تسويقي متوافق مع SEO بالذكاء الاصطناعي.",
    "desc_en": "AI tool for writing SEO-friendly articles and marketing copy."
  },
  {
    "id": "ai-new2-wordtune",
    "category": "ai",
    "url": "https://www.wordtune.com/",
    "domain": "www.wordtune.com",
    "name_ar": "Wordtune",
    "name_en": "Wordtune",
    "desc_ar": "إعادة صياغة الجمل وتحسين أسلوب الكتابة بالذكاء الاصطناعي.",
    "desc_en": "AI tool for rephrasing sentences and improving writing style."
  },
  {
    "id": "ai-new2-rytr",
    "category": "ai",
    "url": "https://rytr.me/",
    "domain": "rytr.me",
    "name_ar": "Rytr",
    "name_en": "Rytr",
    "desc_ar": "كتابة محتوى قصير وسريع بالذكاء الاصطناعي بعدة لغات.",
    "desc_en": "Fast AI short-form content writing in multiple languages."
  },
  {
    "id": "ai-new2-surferseo",
    "category": "ai",
    "url": "https://surferseo.com/",
    "domain": "surferseo.com",
    "name_ar": "Surfer SEO",
    "name_en": "Surfer SEO",
    "desc_ar": "تحليل وتحسين المقالات لتتصدّر نتائج جوجل.",
    "desc_en": "Analyze and optimize articles to rank higher on Google."
  },
  {
    "id": "ai-new2-vidiq",
    "category": "ai",
    "url": "https://vidiq.com/",
    "domain": "vidiq.com",
    "name_ar": "vidIQ",
    "name_en": "vidIQ",
    "desc_ar": "أداة تحليل وتحسين فيديوهات يوتيوب لزيادة المشاهدات.",
    "desc_en": "YouTube video analytics and optimization tool for more views."
  },
  {
    "id": "ai-new2-alliai",
    "category": "ai",
    "url": "https://alli.ai/",
    "domain": "alli.ai",
    "name_ar": "Alli AI",
    "name_en": "Alli AI",
    "desc_ar": "أتمتة تحسين محركات البحث (SEO) لموقعك بالذكاء الاصطناعي.",
    "desc_en": "AI tool that automates on-page SEO for your website."
  },
  {
    "id": "marketing-new2-serpstat",
    "category": "marketing",
    "url": "https://serpstat.com/",
    "domain": "serpstat.com",
    "name_ar": "Serpstat",
    "name_en": "Serpstat",
    "desc_ar": "أداة تحليل الكلمات المفتاحية والمنافسين وتحسين SEO.",
    "desc_en": "Keyword research, competitor analysis and SEO tool."
  },
  {
    "id": "ai-new2-wordlift",
    "category": "ai",
    "url": "https://wordlift.io/",
    "domain": "wordlift.io",
    "name_ar": "WordLift",
    "name_en": "WordLift",
    "desc_ar": "أداة SEO بالذكاء الاصطناعي لتنظيم المحتوى وزيادة الظهور بالبحث.",
    "desc_en": "AI-powered SEO tool that structures content for better search visibility."
  },
  {
    "id": "marketing-new2-simplified",
    "category": "marketing",
    "url": "https://simplified.com/",
    "domain": "simplified.com",
    "name_ar": "Simplified",
    "name_en": "Simplified",
    "desc_ar": "منصة شاملة للتصميم والكتابة والتسويق بالذكاء الاصطناعي بمكان واحد.",
    "desc_en": "All-in-one AI design, writing and marketing platform."
  },
  {
    "id": "marketing-new2-mailchimp",
    "category": "marketing",
    "url": "https://mailchimp.com/",
    "domain": "mailchimp.com",
    "name_ar": "Mailchimp",
    "name_en": "Mailchimp",
    "desc_ar": "منصة تسويق عبر البريد الإلكتروني وأتمتة الحملات.",
    "desc_en": "Email marketing platform with campaign automation."
  },
  {
    "id": "marketing-new2-adcreativeai",
    "category": "marketing",
    "url": "https://www.adcreative.ai/",
    "domain": "www.adcreative.ai",
    "name_ar": "AdCreative AI",
    "name_en": "AdCreative AI",
    "desc_ar": "توليد تصاميم وإعلانات تسويقية عالية التحويل بالذكاء الاصطناعي.",
    "desc_en": "AI-generated ad creatives designed for high conversion."
  },
  {
    "id": "ai-new2-beautifulai",
    "category": "ai",
    "url": "https://www.beautiful.ai/",
    "domain": "www.beautiful.ai",
    "name_ar": "Beautiful.ai",
    "name_en": "Beautiful.ai",
    "desc_ar": "إنشاء عروض تقديمية أنيقة تلقائيًا بالذكاء الاصطناعي.",
    "desc_en": "Automatically creates elegant, well-designed presentations."
  },
  {
    "id": "ai-new2-decktopus",
    "category": "ai",
    "url": "https://www.decktopus.com/",
    "domain": "www.decktopus.com",
    "name_ar": "Decktopus",
    "name_en": "Decktopus",
    "desc_ar": "أداة لإنشاء عروض تقديمية احترافية بسرعة بالذكاء الاصطناعي.",
    "desc_en": "AI tool for quickly creating professional presentations."
  },
  {
    "id": "ai-new2-gamma",
    "category": "ai",
    "url": "https://gamma.app/",
    "domain": "gamma.app",
    "name_ar": "Gamma",
    "name_en": "Gamma",
    "desc_ar": "إنشاء عروض تقديمية ومستندات وصفحات ويب من نص بالذكاء الاصطناعي.",
    "desc_en": "Create presentations, docs and web pages from text using AI."
  },
  {
    "id": "design-new2-designsai",
    "category": "design",
    "url": "https://designs.ai/",
    "domain": "designs.ai",
    "name_ar": "Designs.ai",
    "name_en": "Designs.ai",
    "desc_ar": "مجموعة أدوات تصميم شاملة (شعارات، فيديو، صور) بالذكاء الاصطناعي.",
    "desc_en": "All-in-one AI design suite for logos, video and images."
  },
  {
    "id": "ai-new2-lumen5",
    "category": "ai",
    "url": "https://lumen5.com/",
    "domain": "lumen5.com",
    "name_ar": "Lumen5",
    "name_en": "Lumen5",
    "desc_ar": "تحويل المقالات النصية إلى فيديوهات جاهزة للنشر بالذكاء الاصطناعي.",
    "desc_en": "Turns text articles into ready-to-publish videos using AI."
  },
  {
    "id": "audio-new2-auphonic",
    "category": "audio",
    "url": "https://auphonic.com/",
    "domain": "auphonic.com",
    "name_ar": "Auphonic",
    "name_en": "Auphonic",
    "desc_ar": "تحسين جودة الصوت وضبطه تلقائيًا للبودكاست والفيديو.",
    "desc_en": "Automatically enhances and levels audio for podcasts and video."
  },
  {
    "id": "audio-new2-lovoai",
    "category": "audio",
    "url": "https://lovo.ai/",
    "domain": "lovo.ai",
    "name_ar": "LOVO AI",
    "name_en": "LOVO AI",
    "desc_ar": "تحويل النص إلى صوت احترافي بأصوات ذكاء اصطناعي طبيعية.",
    "desc_en": "Professional AI text-to-speech with natural-sounding voices."
  },
  {
    "id": "app-building-new2-natively",
    "category": "app-building",
    "url": "https://www.natively.dev/",
    "domain": "www.natively.dev",
    "name_ar": "Natively",
    "name_en": "Natively",
    "desc_ar": "بناء تطبيقات جوال حقيقية بكود كامل بمساعدة الذكاء الاصطناعي.",
    "desc_en": "Build real mobile apps with full native code using AI."
  },
  {
    "id": "ai-new2-playablai",
    "category": "ai",
    "url": "https://www.playabl.ai/",
    "domain": "www.playabl.ai",
    "name_ar": "Playabl.ai",
    "name_en": "Playabl.ai",
    "desc_ar": "بناء ألعاب وتجارب تفاعلية عن طريق المحادثة مع الذكاء الاصطناعي.",
    "desc_en": "Build games and interactive experiences by chatting with AI."
  },
  {
    "id": "prompts-fw-swot",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "تحليل SWOT",
    "name_en": "SWOT Analysis",
    "desc_ar": "تحليل نقاط القوة والضعف والفرص والتهديدات.",
    "desc_en": "Analyze strengths, weaknesses, opportunities and threats.",
    "prompt_ar": "علامتنا التجارية تدخل سوقًا جديدًا. حلل نقاط القوة والضعف والفرص والتهديدات مع مراعاة المنافسين والقوانين وفرص النمو.",
    "prompt_en": "Our brand is entering a new market. Analyze the strengths, weaknesses, opportunities and threats, considering competitors, regulations and growth opportunities."
  },
  {
    "id": "prompts-fw-eisenhower",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "مصفوفة أيزنهاور",
    "name_en": "Eisenhower Matrix",
    "desc_ar": "ترتيب المهام حسب الأهمية والاستعجال.",
    "desc_en": "Prioritize tasks by importance and urgency.",
    "prompt_ar": "فريقنا مثقل بالمهام. أنشئ مصفوفة أيزنهاور لتحديد ما يُنفذ، يُفوض، أو يُلغى.",
    "prompt_en": "Our team is overloaded with tasks. Create an Eisenhower Matrix to decide what to do, delegate, or drop."
  },
  {
    "id": "prompts-fw-fishbone",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "مخطط عظم السمكة",
    "name_en": "Fishbone Diagram",
    "desc_ar": "تحليل الأسباب الجذرية للمشكلة.",
    "desc_en": "Analyze the root causes of a problem.",
    "prompt_ar": "ارتفعت معدلات ترك الموظفين للعمل. أنشئ مخطط عظم السمكة لتحديد الأسباب المحتملة.",
    "prompt_en": "Employee turnover has risen. Create a fishbone diagram to identify the possible root causes."
  },
  {
    "id": "prompts-fw-mece",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "مبدأ MECE",
    "name_en": "MECE Principle",
    "desc_ar": "تقسيم شامل بدون تداخل.",
    "desc_en": "A complete breakdown with no overlap.",
    "prompt_ar": "قسّم مستخدمي التطبيق إلى فئات MECE بدون تداخل بين الشرائح.",
    "prompt_en": "Segment our app users into MECE categories with no overlap between segments."
  },
  {
    "id": "prompts-fw-dmaic",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "منهجية DMAIC",
    "name_en": "DMAIC Process",
    "desc_ar": "تحسين العمليات خطوة بخطوة.",
    "desc_en": "Improve processes step by step.",
    "prompt_ar": "تكاليف التوصيل مرتفعة. طبّق منهجية DMAIC لتحديد الهدر وتحسين الأداء.",
    "prompt_en": "Delivery costs are too high. Apply the DMAIC methodology to identify waste and improve performance."
  },
  {
    "id": "prompts-fw-scenario",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "التخطيط بالسيناريوهات",
    "name_en": "Scenario Planning",
    "desc_ar": "التخطيط لعدة سيناريوهات مستقبلية.",
    "desc_en": "Plan for multiple future scenarios.",
    "prompt_ar": "نخطط للتوسع. أنشئ سيناريو أفضل حالة وأسوأ حالة واحتمال مع استراتيجيات مناسبة لكل سيناريو.",
    "prompt_en": "We're planning to expand. Create a best-case, worst-case and likely scenario, each with a matching strategy."
  },
  {
    "id": "prompts-fw-scqa",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "إطار SCQA",
    "name_en": "SCQA Framework",
    "desc_ar": "تنظيم الأفكار والعرض بوضوح.",
    "desc_en": "Organize ideas and present them clearly.",
    "prompt_ar": "استخدم إطار SCQA (الوضع، التعقيد، السؤال، الإجابة) لعرض فكرة جديدة على الإدارة بشكل مقنع.",
    "prompt_en": "Use the SCQA framework (Situation, Complication, Question, Answer) to pitch a new idea to management persuasively."
  },
  {
    "id": "prompts-fw-rapid",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "إطار RAPID",
    "name_en": "RAPID Framework",
    "desc_ar": "توضيح أدوار اتخاذ القرار.",
    "desc_en": "Clarify decision-making roles.",
    "prompt_ar": "استخدم إطار RAPID لتحديد من يوصي، من يوافق، من ينفذ، ومن يقرر بخصوص هذا القرار.",
    "prompt_en": "Use the RAPID framework to define who recommends, agrees, performs, inputs, and decides on this decision."
  },
  {
    "id": "prompts-fw-porter",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "قوى بورتر الخمس",
    "name_en": "Porter's Five Forces",
    "desc_ar": "تحليل قوة المنافسة في السوق.",
    "desc_en": "Analyze competitive forces in a market.",
    "prompt_ar": "قيّم وضع شركتنا التنافسي باستخدام تحليل قوى بورتر الخمس.",
    "prompt_en": "Evaluate our company's competitive position using Porter's Five Forces analysis."
  },
  {
    "id": "prompts-fw-first-principles",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "التفكير بالمبادئ الأولى",
    "name_en": "First Principles Thinking",
    "desc_ar": "إعادة بناء الحل من الصفر.",
    "desc_en": "Rebuild the solution from scratch.",
    "prompt_ar": "فكّك هذه المشكلة إلى مبادئها الأساسية، ثم أعد بناء الحل من الصفر بدون افتراضات جاهزة.",
    "prompt_en": "Break this problem down to its first principles, then rebuild the solution from scratch without assumptions."
  },
  {
    "id": "prompts-fw-decision-matrix",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "مصفوفة القرار",
    "name_en": "Decision Matrix",
    "desc_ar": "المقارنة الموضوعية بين الخيارات.",
    "desc_en": "Objectively compare options.",
    "prompt_ar": "أنشئ مصفوفة قرار لمقارنة الخيارات المتاحة واختيار أفضل نظام HR لشركتنا.",
    "prompt_en": "Create a decision matrix comparing the available options to choose the best HR system for our company."
  },
  {
    "id": "prompts-fw-cost-benefit",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "تحليل التكلفة والعائد",
    "name_en": "Cost-Benefit Analysis",
    "desc_ar": "تحليل التكلفة مقابل العائد.",
    "desc_en": "Compare cost versus benefit.",
    "prompt_ar": "قارن بين بناء نظام مخصص أو استخدام حل جاهز من ناحية التكلفة والعائد على المدى الطويل.",
    "prompt_en": "Compare building a custom system versus using an off-the-shelf solution in terms of long-term cost and benefit."
  },
  {
    "id": "prompts-fw-10-10-10",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "قاعدة 10-10-10",
    "name_en": "10-10-10 Rule",
    "desc_ar": "تقييم القرارات عبر الزمن.",
    "desc_en": "Evaluate decisions across time.",
    "prompt_ar": "قيّم هذا القرار بناءً على شعوري تجاهه بعد 10 دقائق، بعد 10 أشهر، وبعد 10 سنوات.",
    "prompt_en": "Evaluate this decision based on how I'll feel about it in 10 minutes, 10 months, and 10 years."
  },
  {
    "id": "prompts-fw-design-thinking",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "التفكير التصميمي",
    "name_en": "Design Thinking",
    "desc_ar": "حل المشكلات من منظور المستخدم.",
    "desc_en": "Solve problems from the user's perspective.",
    "prompt_ar": "طبّق منهجية التفكير التصميمي (تعاطف، تحديد، ابتكار، نموذج، اختبار) لتحسين تجربة الدفع في تطبيقنا.",
    "prompt_en": "Apply Design Thinking (empathize, define, ideate, prototype, test) to improve the checkout experience in our app."
  },
  {
    "id": "prompts-fw-issue-tree",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "شجرة المشكلات",
    "name_en": "Issue Tree",
    "desc_ar": "تفكيك المشكلات المعقدة.",
    "desc_en": "Break down complex problems.",
    "prompt_ar": "أنشئ شجرة مشكلات (Issue Tree) لتفكيك أسباب انخفاض الإيرادات إلى عناصر قابلة للحل.",
    "prompt_en": "Create an issue tree to break down the causes of declining revenue into solvable pieces."
  },
  {
    "id": "prompts-fw-pareto",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "تحليل باريتو 80/20",
    "name_en": "Pareto Analysis 80/20",
    "desc_ar": "تحديد المؤثر الحقيقي.",
    "desc_en": "Identify the vital few.",
    "prompt_ar": "حدّد الـ20% من الأسباب التي تسبب 80% من المشاكل التي نواجهها حاليًا.",
    "prompt_en": "Identify the 20% of causes responsible for 80% of the problems we're currently facing."
  },
  {
    "id": "prompts-fw-ooda",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "حلقة OODA",
    "name_en": "OODA Loop",
    "desc_ar": "اتخاذ قرارات سريعة.",
    "desc_en": "Make fast decisions.",
    "prompt_ar": "استخدم حلقة OODA (راقب، وجّه، قرّر، نفّذ) للتعامل مع تحركات المنافس المفاجئة.",
    "prompt_en": "Use the OODA loop (Observe, Orient, Decide, Act) to respond to a competitor's sudden move."
  },
  {
    "id": "prompts-fw-six-hats",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "القبعات الست للتفكير",
    "name_en": "Six Thinking Hats",
    "desc_ar": "تحليل متعدد الزوايا.",
    "desc_en": "Analyze from multiple angles.",
    "prompt_ar": "قيّم فكرة الاشتراك الشهري الجديدة باستخدام أسلوب القبعات الست للتفكير.",
    "prompt_en": "Evaluate this new monthly subscription idea using the Six Thinking Hats method."
  },
  {
    "id": "prompts-fw-5whys",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "الأسباب الخمسة (5 Whys)",
    "name_en": "Root Cause Analysis – 5 Whys",
    "desc_ar": "الوصول لجذر المشكلة.",
    "desc_en": "Get to the root cause.",
    "prompt_ar": "اسأل 'لماذا' خمس مرات متتالية للوصول للسبب الحقيقي وراء هذه المشكلة.",
    "prompt_en": "Ask 'why' five times in a row to get to the real root cause behind this problem."
  },
  {
    "id": "prompts-fw-cpm",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "طريقة المسار الحرج",
    "name_en": "Critical Path Method",
    "desc_ar": "إدارة وتنظيم المشاريع.",
    "desc_en": "Manage and organize projects.",
    "prompt_ar": "استخدم طريقة المسار الحرج (CPM) لتحديد المهام الأساسية بمشروعنا وأي تأخير ممكن يأثر على الموعد النهائي.",
    "prompt_en": "Use the Critical Path Method (CPM) to identify the essential tasks in our project and what delays would affect the deadline."
  },
  {
    "id": "prompts-sh-eli5",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "ELI5",
    "name_en": "ELI5",
    "desc_ar": "اشرح لي كأن عمري 5 سنوات.",
    "desc_en": "Explain Like I'm 5",
    "prompt_ar": "اشرح لي كأن عمري 5 سنوات",
    "prompt_en": "Explain like I'm 5 years old"
  },
  {
    "id": "prompts-sh-eli10",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "ELI10",
    "name_en": "ELI10",
    "desc_ar": "اشرح لي كأن عمري 10 سنوات.",
    "desc_en": "Explain Like I'm 10",
    "prompt_ar": "اشرح لي كأن عمري 10 سنوات",
    "prompt_en": "Explain like I'm 10 years old"
  },
  {
    "id": "prompts-sh-tldr-long",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "TL;DR",
    "name_en": "TL;DR",
    "desc_ar": "أعطني الخلاصة (طويل جدًا، ما قرأته).",
    "desc_en": "Too Long; Didn't Read — give me the summary.",
    "prompt_ar": "أعطني الخلاصة، طويل جدًا وما قرأته",
    "prompt_en": "TL;DR — give me the summary"
  },
  {
    "id": "prompts-sh-tldr-short",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "TLDR",
    "name_en": "TLDR",
    "desc_ar": "نفس السابق، تلخيص سريع.",
    "desc_en": "Same as TL;DR, quick summary.",
    "prompt_ar": "لخّصلي بسرعة",
    "prompt_en": "Give me a quick summary"
  },
  {
    "id": "prompts-sh-simple",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "SIMPLE",
    "name_en": "SIMPLE",
    "desc_ar": "بسّط الشرح.",
    "desc_en": "Simplify the explanation.",
    "prompt_ar": "بسّطلي الشرح",
    "prompt_en": "Simplify this for me"
  },
  {
    "id": "prompts-sh-example",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "EXAMPLE",
    "name_en": "EXAMPLE",
    "desc_ar": "أعطني أمثلة.",
    "desc_en": "Give examples.",
    "prompt_ar": "أعطني أمثلة توضيحية",
    "prompt_en": "Give me examples"
  },
  {
    "id": "prompts-sh-top10",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "TOP 10",
    "name_en": "TOP 10",
    "desc_ar": "أعطني أفضل 10 خيارات.",
    "desc_en": "Give me the top 10 options.",
    "prompt_ar": "أعطني أفضل 10 خيارات",
    "prompt_en": "Give me your top 10 options"
  },
  {
    "id": "prompts-sh-stepbystep",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "STEP-BY-STEP",
    "name_en": "STEP-BY-STEP",
    "desc_ar": "اشرح خطوة بخطوة.",
    "desc_en": "Step-by-step instructions.",
    "prompt_ar": "اشرحلي خطوة بخطوة",
    "prompt_en": "Explain this step-by-step"
  },
  {
    "id": "prompts-sh-why",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "WHY",
    "name_en": "WHY",
    "desc_ar": "اشرح السبب.",
    "desc_en": "Explain why.",
    "prompt_ar": "اشرح لي السبب",
    "prompt_en": "Explain why"
  },
  {
    "id": "prompts-sh-how",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "HOW",
    "name_en": "HOW",
    "desc_ar": "اشرح كيفية التنفيذ.",
    "desc_en": "Explain how.",
    "prompt_ar": "اشرح لي كيفية التنفيذ",
    "prompt_en": "Explain how to do this"
  },
  {
    "id": "prompts-sh-proscons",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "PROS/CONS",
    "name_en": "PROS/CONS",
    "desc_ar": "المميزات والعيوب.",
    "desc_en": "Pros and cons.",
    "prompt_ar": "أعطني المميزات والعيوب",
    "prompt_en": "Give me the pros and cons"
  },
  {
    "id": "prompts-sh-summary",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "SUMMARY",
    "name_en": "SUMMARY",
    "desc_ar": "لخّص.",
    "desc_en": "Summarize.",
    "prompt_ar": "لخّصلي هذا",
    "prompt_en": "Summarize this for me"
  },
  {
    "id": "prompts-sh-compare",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "COMPARE",
    "name_en": "COMPARE",
    "desc_ar": "قارن بين الخيارات.",
    "desc_en": "Compare options.",
    "prompt_ar": "قارن بين الخيارات التالية",
    "prompt_en": "Compare the following options"
  },
  {
    "id": "prompts-sh-deepdive",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "DEEP DIVE",
    "name_en": "DEEP DIVE",
    "desc_ar": "تحليل عميق وتفصيلي.",
    "desc_en": "In-depth, detailed analysis.",
    "prompt_ar": "أعطني تحليل عميق وتفصيلي",
    "prompt_en": "Give me a deep, detailed analysis"
  },
  {
    "id": "prompts-sh-table",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "TABLE",
    "name_en": "TABLE",
    "desc_ar": "حوّل المعلومات لجدول.",
    "desc_en": "Format as a table.",
    "prompt_ar": "حوّل هذه المعلومات لجدول",
    "prompt_en": "Format this information as a table"
  },
  {
    "id": "prompts-sh-factcheck",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "FACT CHECK",
    "name_en": "FACT CHECK",
    "desc_ar": "تحقق من صحة المعلومات.",
    "desc_en": "Verify the facts.",
    "prompt_ar": "تحقق من صحة هذه المعلومات",
    "prompt_en": "Fact-check this information"
  },
  {
    "id": "prompts-sh-critique",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "CRITIQUE",
    "name_en": "CRITIQUE",
    "desc_ar": "انتقد وحلل نقاط الضعف.",
    "desc_en": "Critique and find weaknesses.",
    "prompt_ar": "انتقد هذا وحلل نقاط الضعف فيه",
    "prompt_en": "Critique this and point out weaknesses"
  },
  {
    "id": "prompts-sh-list",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "LIST",
    "name_en": "LIST",
    "desc_ar": "اعرضه كقائمة.",
    "desc_en": "Show as a list.",
    "prompt_ar": "اعرض هذا كقائمة",
    "prompt_en": "Show this as a list"
  },
  {
    "id": "prompts-sh-proofread",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "PROOFREAD",
    "name_en": "PROOFREAD",
    "desc_ar": "راجع الأخطاء اللغوية.",
    "desc_en": "Proofread for language errors.",
    "prompt_ar": "راجع الأخطاء اللغوية بهذا النص",
    "prompt_en": "Proofread this text for language errors"
  },
  {
    "id": "prompts-sh-expand",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "EXPAND",
    "name_en": "EXPAND",
    "desc_ar": "وسّع الفكرة.",
    "desc_en": "Expand the idea.",
    "prompt_ar": "وسّع هذه الفكرة",
    "prompt_en": "Expand on this idea"
  },
  {
    "id": "prompts-sh-actionable",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "ACTIONABLE",
    "name_en": "ACTIONABLE",
    "desc_ar": "اجعله خطوات قابلة للتنفيذ.",
    "desc_en": "Make it actionable steps.",
    "prompt_ar": "حوّل هذا لخطوات قابلة للتنفيذ",
    "prompt_en": "Turn this into actionable steps"
  },
  {
    "id": "prompts-sh-rewrite",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "REWRITE",
    "name_en": "REWRITE",
    "desc_ar": "أعد صياغة النص.",
    "desc_en": "Rewrite the text.",
    "prompt_ar": "أعد صياغة هذا النص",
    "prompt_en": "Rewrite this text"
  },
  {
    "id": "prompts-sh-shorten",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "SHORTEN",
    "name_en": "SHORTEN",
    "desc_ar": "اختصر النص.",
    "desc_en": "Shorten the text.",
    "prompt_ar": "اختصر هذا النص",
    "prompt_en": "Shorten this text"
  },
  {
    "id": "prompts-sh-casual",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "CASUAL",
    "name_en": "CASUAL",
    "desc_ar": "اجعل الأسلوب غير رسمي.",
    "desc_en": "Make the tone casual.",
    "prompt_ar": "اجعل أسلوب هذا النص غير رسمي",
    "prompt_en": "Make the tone of this text casual"
  },
  {
    "id": "prompts-sh-pro",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "PRO",
    "name_en": "PRO",
    "desc_ar": "اجعل النتيجة احترافية.",
    "desc_en": "Make it professional.",
    "prompt_ar": "اجعل هذا احترافيًا",
    "prompt_en": "Make this professional"
  },
  {
    "id": "prompts-sh-formal",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "FORMAL",
    "name_en": "FORMAL",
    "desc_ar": "اجعل الأسلوب رسميًا.",
    "desc_en": "Make the tone formal.",
    "prompt_ar": "اجعل أسلوب هذا النص رسميًا",
    "prompt_en": "Make the tone of this text formal"
  },
  {
    "id": "prompts-sh-checklist",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "CHECKLIST",
    "name_en": "CHECKLIST",
    "desc_ar": "حوّلها لقائمة تنفيذ.",
    "desc_en": "Turn it into a checklist.",
    "prompt_ar": "حوّل هذا لقائمة تنفيذ (Checklist)",
    "prompt_en": "Turn this into a checklist"
  },
  {
    "id": "prompts-sh-roleplay",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "ROLEPLAY",
    "name_en": "ROLEPLAY",
    "desc_ar": "تصرف كشخصية أو خبير معين.",
    "desc_en": "Role-play as a specific character or expert.",
    "prompt_ar": "تصرف كأنك خبير في هذا المجال",
    "prompt_en": "Act as an expert in this field"
  },
  {
    "id": "prompts-sh-swot-code",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "SWOT",
    "name_en": "SWOT",
    "desc_ar": "تحليل نقاط القوة والضعف والفرص والتهديدات.",
    "desc_en": "SWOT Analysis.",
    "prompt_ar": "اعمل تحليل SWOT لهذا الموضوع",
    "prompt_en": "Do a SWOT analysis on this topic"
  },
  {
    "id": "prompts-sh-oneliner",
    "category": "prompts",
    "type": "prompt",
    "url": "",
    "domain": "",
    "name_ar": "ONE-LINER",
    "name_en": "ONE-LINER",
    "desc_ar": "أعطني الإجابة بسطر واحد.",
    "desc_en": "Give the answer in one line.",
    "prompt_ar": "أعطني الإجابة بسطر واحد فقط",
    "prompt_en": "Give me the answer in a single line"
  }
];
